import Image from "next/image";
import Link from "next/link";
import { pageMetadata } from "@/lib/seo";
import s from "./about.module.css";
export const metadata = pageMetadata("/about", "About JovaMedia | Our Values & Culture", "Discover the values behind JovaMedia: clear thinking, thoughtful design and a collaborative approach to websites, brands and digital experiences.");
const values = [
 ["01","Clarity before complexity","We ask what the work needs to achieve before deciding what to make. Clear priorities help every design and development decision have a purpose."],
 ["02","Care in the details","The words, the layout, the mobile experience and the small interactions all matter. We consider how they work together, not just how they look on their own."],
 ["03","Honest advice","We explain the options and tradeoffs in plain language. If a simpler approach would serve your business better, that is the conversation we want to have."],
 ["04","Shared ownership","Your knowledge of your business is part of the work. We bring our perspective, make room for yours and agree the direction together."]
];
export default function Page(){return <main className={s.about}>
 <section className={`page-hero ${s.hero}`}><div className="shell"><p className="kicker">ABOUT JOVAMEDIA</p><h1>Good work starts<br/><em>with good people.</em></h1><p className="lead">We are a digital partner for businesses ready to move forward. We bring clear thinking, thoughtful design and practical technology to the same table.</p><div className="actions"><Link className="btn" href="/contact">Let’s get to know your business</Link></div></div></section>
 <section className={s.perspective}><div className={`shell ${s.split}`}><div><p className="kicker">WHAT WE BELIEVE</p><h2>Your business deserves<br/><em>more than a template.</em></h2></div><div><p className={s.lead}>A website should feel like your business, speak to your customers and make their next step easier.</p><p>That starts with listening. What are you trying to change? What do people need to understand? What is getting in the way today?</p><p>We connect the answers across design, content and development, so the finished work feels considered from the first impression to the final interaction.</p></div></div></section>
 <section className={s.values}><div className="shell"><header><p className="kicker">OUR VALUES</p><h2>What matters to us.<br/><em>What you can expect.</em></h2></header><div className={s.valueGrid}>{values.map(([,title,copy])=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
 <section className={s.culture}><div className={`shell ${s.cultureGrid}`}><div className={s.photo}><Image src="/home-agency/sketch.webp" alt="Design ideas and sketches being developed at a shared workspace" fill sizes="(max-width:700px) 90vw, 45vw"/></div><div><p className="kicker">OUR CULTURE</p><h2>Curious by nature.<br/><em>Collaborative by choice.</em></h2><p>We like useful questions, fresh perspectives and conversations that make an idea better. You do not need to arrive with all the answers.</p><div className={s.cultureNotes}><div><h3>Room to explore</h3><p>We look beyond the first idea and discuss what will genuinely help your audience.</p></div><div><h3>Easy to work with</h3><p>Plain language, constructive feedback and a shared understanding of the next step.</p></div><div><h3>Thoughtful use of technology</h3><p>We choose tools around the task, with human judgement guiding what gets delivered.</p></div></div></div></div></section>
 <section className={s.invitation}><div className="shell"><p className="kicker">A GOOD FIT STARTS WITH A CONVERSATION</p><h2>Tell us where you want to go.</h2><p>A new idea, a website that needs attention or a brand ready for its next chapter. We would love to hear about it.</p><Link href="/contact" className="btn">Talk to Jova</Link></div></section>
 </main>}
