import Link from 'next/link'; import {services,principles} from '@/lib/data';
const featured=services.slice(0,6);
export default function Home(){return <main>
<section className="hero"><div className="shell hero-inner"><div className="kicker">Independent digital media agency · London</div><h1>Digital work that<br/><span>earns attention.</span></h1><p className="lead">JovaMedia helps growing businesses sharpen their brand, reach the right people and turn digital activity into measurable commercial progress.</p><div className="actions"><Link className="btn" href="/contact">Start a project</Link><Link className="text-link" href="/services">Explore services →</Link></div><div className="hero-rule"><span>Strategy</span><span>Creative</span><span>Media</span><span>Technology</span></div></div></section>
<section className="band band-navy"><div className="shell band-grid"><div className="kicker">What we solve</div><h2>Your channels should work together, not compete for attention.</h2><p>We connect brand, content, social, paid media, search and web around one plan. Fewer disconnected activities. Clearer priorities. Better decisions.</p></div></section>
<section className="section"><div className="shell"><div className="section-head"><div><div className="kicker">Capabilities</div><h2>Specialists where you need them. One team around the outcome.</h2></div><p>Use JovaMedia for a focused brief or bring several disciplines together around a larger growth objective.</p></div><div className="feature-service-grid">{featured.map((s,i)=><Link href={'/services/'+s.slug} className={`feature-service tone-${(i%3)+1}`} key={s.slug}><span className="service-no">0{i+1}</span><small>{s.eyebrow}</small><h3>{s.name}</h3><p>{s.summary}</p><b>View service →</b></Link>)}</div><div className="center-action"><Link href="/services" className="btn outline">View all capabilities</Link></div></div></section>
<section className="band band-gold"><div className="shell statement"><div className="kicker">A clearer agency relationship</div><h2>Know what is being done, what it is meant to change and what happens next.</h2><Link href="/about" className="text-link">How JovaMedia works →</Link></div></section>
<section className="section"><div className="shell"><div className="section-head"><div><div className="kicker">Why JovaMedia</div><h2>Senior thinking stays close to delivery.</h2></div><p>No inflated team for the sake of it. We shape the work around the problem and keep communication direct.</p></div><div className="principles">{principles.map(([a,b],i)=><div key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></div>)}</div></div></section>
<section className="band band-soft"><div className="shell split promo-split"><div><div className="kicker">Connected digital</div><h2>Attention is only useful when the rest of the journey holds up.</h2></div><div className="prose"><p>We look beyond the post or advert. Landing pages, search visibility, messaging, conversion paths and reporting all influence what happens after someone notices you.</p><p>That wider view helps us recommend the work that matters instead of selling a channel by default.</p><Link className="btn" href="/services">See our services</Link></div></div></section>
<section className="section"><div className="shell"><div className="section-head"><div><div className="kicker">Work</div><h2>Proof should be specific.</h2></div><p>As client work is approved for publication, our case studies will show the brief, the decisions, the delivery and the outcome. No invented logos or anonymous performance claims.</p></div><div className="work-placeholder"><div><small>CASE STUDIES</small><h3>Work worth explaining properly.</h3><p>Our public case-study library will grow as projects become available to share.</p></div><Link href="/work">Our approach →</Link></div></div></section>
</main>}
