"use client";
/* eslint-disable @next/next/no-img-element */
import { useEffect, useRef } from "react";
import Link from "next/link";
import styles from "./DaybreakHero.module.css";

function CoffeeSite(){return (<article className="siteCopy coffeeSite">
<div className="coffeeNav"><strong><i aria-hidden="true"></i>daybreak<span>coffee, daily.</span></strong><span>Our menu &nbsp;&nbsp; Rewards &nbsp;&nbsp; Our story &nbsp;&nbsp; <b>Find us</b></span><i className="coffeeMobileMenu">☰</i></div>
<div className="coffeeHero"><span className="coffeeKicker">Made for your morning</span><span className="coffeeOutline">COFFEE.</span><h2>Good coffee.<br/>Better days.</h2><p>Small-batch roasts and fresh bakes,<br/>ready when you are.</p><span className="coffeeButton">See the menu ↗</span><div className="leafLayer"><img src="/hero-daybreak/leaves.png" alt="" width="1200" height="939"/></div><div className="productLayer"><img src="/hero-daybreak/coffee-cup.png" alt="" width="1141" height="1060"/></div><div className="beanLayer"><img src="/hero-daybreak/beans.png" alt="" width="230" height="230"/></div></div>
<div className="coffeeRibbon"><span>GOOD COFFEE. GOOD COMPANY.</span></div>
<div className="coffeeMenu"><div className="menuIntro"><h3>Find your favourite.</h3><span>Coffee &nbsp; Iced &nbsp; Bakes</span></div><div className="menuProducts"><div className="menuProduct"><div className="productPhoto cupPhoto"><img src="/hero-daybreak/coffee-cup.png" alt="" width="1141" height="1060"/></div><strong>Proper flat white <span>+</span></strong><small>Velvety milk. A little morning magic.</small></div><div className="menuProduct"><div className="productPhoto icedPhoto"><img src="/hero-daybreak/coffee-glass.jpg" alt="" width="1600" height="2400"/></div><strong>Iced & easy <span>+</span></strong><small>Cool, creamy, everyday goodness.</small></div><div className="menuProduct"><div className="productPhoto"><img src="/hero-daybreak/croissant.jpg" alt="" width="1200" height="1800"/></div><strong>Golden mornings <span>+</span></strong><small>Fresh from the oven, every morning.</small></div></div></div>
<div className="coffeeClub"><span>Your daily ritual, rewarded.</span><h3>Good coffee.<br/>Great company.</h3><p>A little thank you for making us part of your day.</p><span className="coffeeButton">Join the Daybreak Club</span><div className="clubCard"><strong>daybreak<span>club</span></strong><div className="clubStamps"><i></i><i></i><i></i><i></i><i></i><i></i></div><small>Your next good day is on us.</small></div></div><div className="coffeeFooter"><span>See you in the morning.</span><strong>daybreak</strong><span>Our menu &nbsp;&nbsp; Our story &nbsp;&nbsp; Find us</span></div></article>);}

export default function DaybreakHero(){
 const root=useRef(null);
 useEffect(()=>{
  const el=root.current,showcase=el.querySelector('.showcase'),tracks=[...el.querySelectorAll('.scrollTrack')],toggle=el.querySelector('#motion-toggle'),media=matchMedia('(prefers-reduced-motion: reduce)');
  let disposed=false,manualPause=false,visible=true,frame=0;
  const measure=()=>{for(const track of tracks){const copies=[...track.children];copies.forEach(copy=>copy.style.height='auto');const height=Math.ceil(copies[0].getBoundingClientRect().height);copies.forEach(copy=>copy.style.height=height+'px');track.style.setProperty('--loop-end',-height+'px');}};
  const paint=()=>{frame=0;for(const track of tracks){const animation=track.getAnimations()[0],time=animation&&Number(animation.currentTime)||0,phase=(time%20000)/20000,progress=Math.max(0,Math.min(1,(phase-.1)/.8)),distance=-parseFloat(track.style.getPropertyValue('--loop-end'))||0;for(const copy of track.children){const hero=copy.querySelector('.coffeeHero'),scroll=media.matches?0:Math.max(0,Math.min(hero.offsetHeight,distance*progress-copy.offsetTop-hero.offsetTop));hero.style.setProperty('--product-y',scroll*.12+'px');hero.style.setProperty('--product-angle',scroll*.012+'deg');hero.style.setProperty('--outline-y',-scroll*.1+'px');hero.style.setProperty('--leaf-y',-scroll*.08+'px');hero.style.setProperty('--bean-y',scroll*.06+'px');}}if(!disposed&&!manualPause&&visible&&!document.hidden&&!media.matches)frame=requestAnimationFrame(paint);};
  const sync=()=>{showcase.classList.toggle('paused',manualPause||!visible||document.hidden||media.matches);cancelAnimationFrame(frame);paint();};
  const click=()=>{manualPause=!manualPause;toggle.setAttribute('aria-pressed',String(manualPause));toggle.querySelector('.controlText').textContent=manualPause?'Play preview':'Pause preview';toggle.querySelector('.controlIcon').textContent=manualPause?'▷':'Ⅱ';sync();};
  const resize=new ResizeObserver(measure);tracks.forEach(track=>resize.observe(track.parentElement));
  const intersection=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;sync();});intersection.observe(el);
  toggle.addEventListener('click',click);document.addEventListener('visibilitychange',sync);media.addEventListener('change',sync);
  Promise.all([document.fonts.ready,...[...el.querySelectorAll('img')].map(img=>img.decode().catch(()=>{}))]).then(()=>{if(disposed)return;measure();showcase.classList.add('ready');sync();});
  return()=>{disposed=true;cancelAnimationFrame(frame);resize.disconnect();intersection.disconnect();toggle.removeEventListener('click',click);document.removeEventListener('visibilitychange',sync);media.removeEventListener('change',sync);};
 },[]);
 return <section ref={root} className={styles.root} aria-labelledby="home-title"><div className="shell"><div className="hero"><div className="message"><h1 id="home-title">Good ideas.<br/>Better websites.<br/><span>Brighter businesses.</span></h1><p className="description">We bring websites, brands and digital experiences together to help your business move forward.</p><div className="actions"><Link className="primary" href="/contact">Start a project</Link><Link className="secondary" href="/services/web-design">Explore web design</Link></div><div className="facts"><div><strong>8</strong><span>Services under one roof</span></div><div><strong>4</strong><span>Clear project stages</span></div></div></div><div className="showcase"><div className="backdrop" aria-hidden="true"></div><div className="browser device" aria-hidden="true"><div className="browserBar"><span className="dots"><i></i><i></i><i></i></span><span className="address">daybreak.coffee</span><span className="browserPlus">+</span></div><div className="screen"><div className="scrollTrack" data-screen="desktop">{[0,1].map(copy => <CoffeeSite key={copy}/>)}</div></div></div><div className="launch"><span>Your new website</span><strong>Ready to launch</strong><div className="stages"><span>Design</span><span>Build</span><span>Launch</span></div></div><div className="built"><strong><span aria-hidden="true">✓</span> Designed & built</strong><span>by JovaMedia, for every screen</span></div><div className="phone device" aria-hidden="true"><div className="phoneSpeaker"></div><div className="screen"><div className="scrollTrack" data-screen="phone">{[0,1].map(copy => <CoffeeSite key={copy}/>)}</div></div></div><div className="enquiry"><span className="enquiryIcon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><rect x="3" y="5" width="18" height="14" rx="3"/><path d="m4 7 8 6 8-6"/></svg></span><div><strong>New enquiry</strong><span>Let’s make something great.</span></div><small>now</small></div><div className="motionControl"><button type="button" id="motion-toggle" aria-pressed="false"><span aria-hidden="true" className="controlIcon">Ⅱ</span><span className="controlText">Pause preview</span></button><span>An original coffee website concept.</span></div></div></div></div></section>;
}
