export const services = [
 {slug:'web-design',name:'Web Design & Development',eyebrow:'Web',summary:'Fast, conversion-focused websites built around your commercial goals.',desc:'Strategy, UX, copy structure and Next.js development in one joined-up website engagement.',deliverables:['Discovery and sitemap','UX and responsive design','Next.js development','Technical SEO foundations','Analytics and conversion tracking','Launch support'],from:'From £2,500'},
 {slug:'seo',name:'SEO & Search',eyebrow:'Search',summary:'Technical and content-led SEO built to create qualified organic demand.',desc:'We prioritise search opportunities with commercial intent, then improve the technical foundation, content and authority needed to compete.',deliverables:['Technical SEO audit','Keyword and competitor research','On-page optimisation','Content roadmap','Internal linking','Monthly reporting'],from:'From £900/month'},
 {slug:'paid-media',name:'Paid Media',eyebrow:'Performance',summary:'Google and paid social campaigns designed around profitable acquisition.',desc:'Campaign strategy, build, creative direction and optimisation with transparent reporting against the metrics that matter.',deliverables:['Account audit and strategy','Campaign build','Tracking review','Creative testing plan','Weekly optimisation','Monthly performance report'],from:'From £750/month'},
 {slug:'social-media',name:'Social Media',eyebrow:'Social',summary:'A consistent content system that keeps your brand useful and visible.',desc:'Channel strategy, content planning and production support without filler content or vanity reporting.',deliverables:['Channel strategy','Monthly content plan','Copy and creative direction','Publishing support','Community guidance','Performance review'],from:'From £800/month'},
 {slug:'content',name:'Content & Copy',eyebrow:'Content',summary:'Commercial content for search, campaigns, websites and nurture.',desc:'Clear content grounded in customer intent, brand voice and the action you want the reader to take.',deliverables:['Content strategy','Website copy','SEO articles','Landing pages','Email copy','Content refreshes'],from:'From £450/project'},
 {slug:'brand-strategy',name:'Brand Strategy',eyebrow:'Brand',summary:'Positioning and messaging that makes your business easier to understand and choose.',desc:'We turn customer insight and competitive context into a practical brand system your team can use.',deliverables:['Competitor review','Positioning','Audience definition','Messaging framework','Tone of voice','Visual direction'],from:'From £1,500'}
];
export const principles=[['Senior attention','You work directly with the people shaping the strategy and delivery.'],['Commercial focus','We tie activity to qualified leads, revenue and measurable business outcomes.'],['Clear reporting','Plain-English reporting. You see what changed, why it changed and what happens next.'],['Flexible engagement','No artificial lock-ins. Scope and cadence should earn their place.']];
export const siteConfig = {
  name: "Jova Media",
  url: "https://jovamedia.com",
  email: "support@jovamedia.com",
};