import {createClient} from '@supabase/supabase-js';
import fs from 'node:fs';
export function credentials(){let url=process.env.BOOKING_SUPABASE_URL,key=process.env.BOOKING_SUPABASE_SECRET_KEY;if(!key&&fs.existsSync('.env.local')){const raw=fs.readFileSync('.env.local','utf8');url=raw.match(/^BOOKING_SUPABASE_URL=(.+)$/m)?.[1];key=raw.match(/^BOOKING_SUPABASE_SECRET_KEY=(.+)$/m)?.[1];}if(!key)throw new Error('SETUP_REQUIRED');return {url,key};}
export function db(){const {url,key}=credentials();return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});}
export async function rows(query){const {data,error}=await query;if(error)throw error;return data;}
export const publicBusiness='id,name,slug,phone,email,address,timezone,currency,minimum_notice_minutes,booking_window_days,cancellation_notice_hours,description,accent_color';
export function cookiesFor(session){const options=`Path=/preview/booking; HttpOnly; SameSite=Lax; ${process.env.NODE_ENV==='production'?'Secure; ':''}`;return [`booking_access=${session.access_token}; ${options}Max-Age=${session.expires_in}`,`booking_refresh=${session.refresh_token}; ${options}Max-Age=2592000`];}
export async function identity(req){const access=req.cookies.get('booking_access')?.value;if(!access)return null;const client=db();const {data,error}=await client.auth.getUser(access);if(error)return null;const members=await rows(client.from('business_members').select('*').eq('user_id',data.user.id));return {user:data.user,members};}
const rate=new Map();export function throttle(key,max=20){const now=Date.now();let item=rate.get(key);if(!item||now>item.until){item={count:0,until:now+600000};rate.set(key,item);}if(rate.size>10000)for(const [k,v] of rate)if(v.until<now)rate.delete(k);if(++item.count>max)throw Object.assign(new Error('Too many attempts. Try again in ten minutes.'),{status:429});}
export function sameOrigin(req){const origin=req.headers.get('origin');if(origin&&new URL(origin).host!==req.headers.get('host'))throw Object.assign(new Error('Request not allowed'),{status:403});}
