-- Hosted column, constraint, index, function and trigger definitions exported 2026-10-10.
-- Auth schema and roles below are isolated test doubles. No customer records are included.
create role anon;create role authenticated;create role service_role bypassrls;
create schema auth;create schema extensions;
create extension btree_gist with schema extensions;
set search_path=public,extensions,pg_temp;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;
create table public.bookings (id bigint generated always as identity not null, business_id bigint not null, staff_id bigint not null, service_id bigint not null, customer_name text not null, customer_email text, customer_phone text, starts_at timestamp with time zone not null, ends_at timestamp with time zone not null, buffer_minutes integer default 0 not null, reserved_until timestamp with time zone not null, price_pence integer not null, status text default 'confirmed'::text not null, request_id uuid default gen_random_uuid() not null, created_at timestamp with time zone default now() not null, client_id bigint not null);
create table public.business_members (business_id bigint not null, user_id uuid not null, role text not null, username text);
create table public.businesses (id bigint generated by default as identity not null, name text not null, slug text not null, phone text, email text, address text, timezone text default 'Europe/London'::text not null, currency text default 'GBP'::text not null, minimum_notice_minutes integer default 60 not null, booking_window_days integer default 60 not null, cancellation_notice_hours integer default 24 not null, active boolean default true not null, created_at timestamp with time zone default now() not null, description text default ''::text not null, accent_color text default '#285D8E'::text not null);
create table public.clients (id bigint generated always as identity not null, business_id bigint not null, name text not null, email text, phone text, notes text default ''::text not null, created_at timestamp with time zone default now() not null, user_id uuid);
create table public.service_categories (id bigint generated always as identity not null, business_id bigint not null, name text not null, sort_order integer default 0 not null, created_at timestamp with time zone default now() not null);
create table public.services (id bigint generated always as identity not null, business_id bigint not null, name text not null, price_pence integer not null, duration_minutes integer not null, buffer_minutes integer default 0 not null, active boolean default true not null, category_id bigint);
create table public.staff (id bigint generated always as identity not null, business_id bigint not null, name text not null, active boolean default true not null);
create table public.staff_services (business_id bigint not null, staff_id bigint not null, service_id bigint not null);
create table public.time_off (id bigint generated always as identity not null, business_id bigint not null, staff_id bigint not null, starts_at timestamp with time zone not null, ends_at timestamp with time zone not null, reason text);
create table public.working_hours (id bigint generated always as identity not null, business_id bigint not null, staff_id bigint not null, weekday smallint not null, opens_at time without time zone not null, closes_at time without time zone not null);
alter table bookings add constraint bookings_business_id_request_id_key UNIQUE (business_id, request_id);
alter table bookings add constraint bookings_pkey PRIMARY KEY (id);
alter table business_members add constraint business_members_pkey PRIMARY KEY (business_id, user_id);
alter table businesses add constraint businesses_pkey PRIMARY KEY (id);
alter table businesses add constraint businesses_slug_key UNIQUE (slug);
alter table clients add constraint clients_business_id_id_key UNIQUE (business_id, id);
alter table clients add constraint clients_pkey PRIMARY KEY (id);
alter table service_categories add constraint service_categories_business_id_id_key UNIQUE (business_id, id);
alter table service_categories add constraint service_categories_pkey PRIMARY KEY (id);
alter table services add constraint services_business_id_id_key UNIQUE (business_id, id);
alter table services add constraint services_pkey PRIMARY KEY (id);
alter table staff add constraint staff_business_id_id_key UNIQUE (business_id, id);
alter table staff add constraint staff_pkey PRIMARY KEY (id);
alter table staff_services add constraint staff_services_pkey PRIMARY KEY (business_id, staff_id, service_id);
alter table time_off add constraint time_off_pkey PRIMARY KEY (id);
alter table working_hours add constraint working_hours_pkey PRIMARY KEY (id);
alter table bookings add constraint bookings_buffer_minutes_check CHECK ((buffer_minutes >= 0));
alter table bookings add constraint bookings_business_id_staff_id_service_id_fkey FOREIGN KEY (business_id, staff_id, service_id) REFERENCES staff_services(business_id, staff_id, service_id);
alter table bookings add constraint bookings_check CHECK ((ends_at > starts_at));
alter table bookings add constraint bookings_check1 CHECK ((reserved_until = (ends_at + ((buffer_minutes)::double precision * '00:01:00'::interval))));
alter table bookings add constraint bookings_check2 CHECK (((NULLIF(TRIM(BOTH FROM customer_email), ''::text) IS NOT NULL) OR (NULLIF(TRIM(BOTH FROM customer_phone), ''::text) IS NOT NULL)));
alter table bookings add constraint bookings_client_fk FOREIGN KEY (business_id, client_id) REFERENCES clients(business_id, id);
alter table bookings add constraint bookings_customer_name_check CHECK ((length(TRIM(BOTH FROM customer_name)) > 0));
alter table bookings add constraint bookings_price_pence_check CHECK ((price_pence >= 0));
alter table bookings add constraint bookings_staff_id_tstzrange_excl EXCLUDE USING gist (staff_id WITH =, tstzrange(starts_at, reserved_until, '[)'::text) WITH &&) WHERE ((status <> 'cancelled'::text));
alter table bookings add constraint bookings_status_check CHECK ((status = ANY (ARRAY['confirmed'::text, 'cancelled'::text, 'completed'::text, 'no_show'::text])));
alter table business_members add constraint business_members_role_check CHECK ((role = ANY (ARRAY['owner'::text, 'staff'::text])));
alter table businesses add constraint businesses_booking_window_days_check CHECK ((booking_window_days > 0));
alter table businesses add constraint businesses_cancellation_notice_hours_check CHECK ((cancellation_notice_hours >= 0));
alter table businesses add constraint businesses_minimum_notice_minutes_check CHECK ((minimum_notice_minutes >= 0));
alter table businesses add constraint businesses_name_check CHECK ((length(TRIM(BOTH FROM name)) > 0));
alter table businesses add constraint businesses_slug_check CHECK ((slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'::text));
alter table clients add constraint clients_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses(id);
alter table clients add constraint clients_check CHECK (((NULLIF(TRIM(BOTH FROM email), ''::text) IS NOT NULL) OR (NULLIF(TRIM(BOTH FROM phone), ''::text) IS NOT NULL)));
alter table clients add constraint clients_name_check CHECK (((length(TRIM(BOTH FROM name)) >= 1) AND (length(TRIM(BOTH FROM name)) <= 150)));
alter table clients add constraint clients_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table service_categories add constraint service_categories_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses(id);
alter table service_categories add constraint service_categories_name_check CHECK (((length(TRIM(BOTH FROM name)) >= 1) AND (length(TRIM(BOTH FROM name)) <= 100)));
alter table service_categories add constraint service_categories_sort_order_check CHECK (((sort_order >= 0) AND (sort_order <= 10000)));
alter table services add constraint services_buffer_minutes_check CHECK ((buffer_minutes >= 0));
alter table services add constraint services_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses(id);
alter table services add constraint services_category_business_fk FOREIGN KEY (business_id, category_id) REFERENCES service_categories(business_id, id);
alter table services add constraint services_duration_minutes_check CHECK ((duration_minutes > 0));
alter table services add constraint services_price_pence_check CHECK ((price_pence >= 0));
alter table staff add constraint staff_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses(id);
alter table staff_services add constraint staff_services_business_id_service_id_fkey FOREIGN KEY (business_id, service_id) REFERENCES services(business_id, id);
alter table staff_services add constraint staff_services_business_id_staff_id_fkey FOREIGN KEY (business_id, staff_id) REFERENCES staff(business_id, id);
alter table time_off add constraint time_off_business_id_staff_id_fkey FOREIGN KEY (business_id, staff_id) REFERENCES staff(business_id, id);
alter table time_off add constraint time_off_check CHECK ((ends_at > starts_at));
alter table working_hours add constraint working_hours_business_id_staff_id_fkey FOREIGN KEY (business_id, staff_id) REFERENCES staff(business_id, id);
alter table working_hours add constraint working_hours_check CHECK ((closes_at > opens_at));
alter table working_hours add constraint working_hours_staff_id_weekday_tsrange_excl EXCLUDE USING gist (staff_id WITH =, weekday WITH =, tsrange(('2000-01-01'::date + opens_at), ('2000-01-01'::date + closes_at), '[)'::text) WITH &&);
alter table working_hours add constraint working_hours_weekday_check CHECK (((weekday >= 0) AND (weekday <= 6)));
CREATE INDEX bookings_business_start_idx ON public.bookings USING btree (business_id, starts_at);
CREATE INDEX business_members_user_idx ON public.business_members USING btree (user_id, business_id);
CREATE UNIQUE INDEX business_members_username_unique ON public.business_members USING btree (lower(username)) WHERE (username IS NOT NULL);
CREATE INDEX clients_business_idx ON public.clients USING btree (business_id);
CREATE UNIQUE INDEX clients_business_user_unique ON public.clients USING btree (business_id, user_id) WHERE (user_id IS NOT NULL);
CREATE UNIQUE INDEX service_categories_name_unique ON public.service_categories USING btree (business_id, lower(TRIM(BOTH FROM name)));
CREATE INDEX services_category_idx ON public.services USING btree (business_id, category_id);
CREATE INDEX time_off_staff_start_idx ON public.time_off USING btree (staff_id, starts_at);
CREATE OR REPLACE FUNCTION public.create_booking(p_business bigint, p_staff bigint, p_service bigint, p_start timestamp with time zone, p_name text, p_email text, p_phone text, p_request uuid, p_client bigint DEFAULT NULL::bigint)
 RETURNS bookings
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$ declare c bigint; result public.bookings; begin
perform pg_advisory_xact_lock(hashtextextended(p_business::text||p_request::text,0)); select * into result from public.bookings where business_id=p_business and request_id=p_request; if found then return result; end if; c=p_client;
if c is null then insert into public.clients(business_id,name,email,phone) values(p_business,p_name,nullif(p_email,''),nullif(p_phone,'')) returning id into c; end if;
insert into public.bookings(business_id,staff_id,service_id,client_id,customer_name,customer_email,customer_phone,starts_at,ends_at,reserved_until,price_pence,request_id) values(p_business,p_staff,p_service,c,p_name,nullif(p_email,''),nullif(p_phone,''),p_start,p_start+interval '1 minute',p_start+interval '1 minute',0,p_request) returning * into result; return result; end $function$
;
CREATE OR REPLACE FUNCTION public.validate_booking()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$ declare b public.businesses; s public.services; local_start timestamp; local_end timestamp; begin
if tg_op='UPDATE' and new.business_id=old.business_id and new.staff_id=old.staff_id and new.service_id=old.service_id and new.starts_at=old.starts_at and not(old.status='cancelled' and new.status<>'cancelled') then new.ends_at=old.ends_at; new.buffer_minutes=old.buffer_minutes; new.reserved_until=old.reserved_until; new.price_pence=old.price_pence; return new; end if;
perform 1 from public.staff where id=new.staff_id and business_id=new.business_id and active for update; if not found then raise exception 'Staff member unavailable'; end if;
select * into b from public.businesses where id=new.business_id and active; if not found then raise exception 'Business unavailable'; end if;
select * into s from public.services where id=new.service_id and business_id=new.business_id and active; if not found then raise exception 'Service unavailable'; end if;
if new.starts_at<now()+make_interval(mins=>b.minimum_notice_minutes) or new.starts_at>now()+make_interval(days=>b.booking_window_days) then raise exception 'Outside booking window'; end if;
new.ends_at=new.starts_at+make_interval(mins=>s.duration_minutes); new.buffer_minutes=s.buffer_minutes; new.reserved_until=new.ends_at+make_interval(mins=>s.buffer_minutes); new.price_pence=s.price_pence;
local_start=new.starts_at at time zone b.timezone; local_end=new.reserved_until at time zone b.timezone;
if local_start::date<>local_end::date or not exists(select 1 from public.working_hours w where w.business_id=new.business_id and w.staff_id=new.staff_id and w.weekday=extract(dow from local_start) and w.opens_at<=local_start::time and w.closes_at>=local_end::time) then raise exception 'Outside working hours'; end if;
if exists(select 1 from public.time_off t where t.staff_id=new.staff_id and tstzrange(t.starts_at,t.ends_at,'[)') && tstzrange(new.starts_at,new.reserved_until,'[)')) then raise exception 'Staff member is on time off'; end if; return new; end $function$
;
CREATE OR REPLACE FUNCTION public.validate_time_off()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$ begin perform 1 from public.staff where id=new.staff_id and business_id=new.business_id for update;
if exists(select 1 from public.bookings b where b.staff_id=new.staff_id and b.status<>'cancelled' and tstzrange(b.starts_at,b.reserved_until,'[)') && tstzrange(new.starts_at,new.ends_at,'[)')) then raise exception 'Move or cancel appointments before blocking this time'; end if; return new; end $function$
;
CREATE TRIGGER booking_availability BEFORE INSERT OR UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION validate_booking();
CREATE TRIGGER time_off_availability BEFORE INSERT OR UPDATE ON public.time_off FOR EACH ROW EXECUTE FUNCTION validate_time_off();
grant usage,select on all sequences in schema public to authenticated,service_role;
